#!/bin/bash

if [ ! -d dbs ]
then
  mkdir dbs
  echo -e "\e[42mThe folder for databases is created successfully\e[0m"
fi

COLUMNS=0
select choice in "Create Database" "List Database" "Connect To Database" "Drop Database" "Exit"
do
case $REPLY in
1)echo "Enter your database name"
       read answer
 while [ -z "$answer" ]
      do
           echo           
           echo  -e "\e[41mYou must enter a name\e[0m"
           echo           
           read -e -p "Enter the name of the database you want to create > " answer
           echo           
      done
while [[ $answer = *" "* ]]; do
		echo -e "\e[41mThe name can't contain spaces\e[0m"
read -e -p "Enter the name of the database you want to create > " answer
           echo           
      done

	while  [[ ^$answer =~ [1-9:!\|@\{#$%\&*\`~+=?.\>\<,\;:\_\-\ ] ]]; do
		echo -e "\e[41mYou can't enter these characters \e[0m"
		read -e -p "Enter the name of the database you want to create > " answer
           echo           
      done
	while  [[ -e ./dbs/$answer ]]; do
		echo  -e "\e[41mThis database name is already used\e[0m"
	read -e -p "Enter the name of the database you want to create > " answer
           echo           
      done
	   if  [[ $answer =~ ^[a-zA-Z] ]]; then
		mkdir ./dbs/$answer
      echo -e "\e[42mDatabase created sucessfully \e[0m"
	
	
	else
		echo -e "\e[41mDatabase name can't start with numbers or special characters\e[0m"
	fi



;;
2)  echo The databases are:
                   cd ./dbs
                     ./../borderlist.sh
                  
                      cd ..
			;;
3) read -e -p "Enter the database you want to connect with > " dbname
      while [ -z "$dbname" ]
      do
           echo           
           echo  -e "\e[41mYou must enter a name\e[0m"
           echo           
           read -e -p "Enter the name of the database you want to connect to > " dbname
           echo           
      done

     while [ ! -d ./dbs/$dbname ]
    do
          echo -e "\e[41mThis database doesn't exist\e[0m"
      read -e -p "Enter the name of the database you want to connect to > " dbname
           echo           
      done

     if [ -d ./dbs/$dbname ]
     then
          gnome-terminal -- bash -c "./secondarymenu.sh $dbname; bash" > /dev/null

	fi
;;
4)  echo "Enter database name you want to delete"
       read name
      while [ -z "$name" ]
      do
           echo           
           echo  -e "\e[41mYou must enter a name\e[0m"
           echo           
           read -e -p "Enter the name of the database you want to delete > " name
           echo           
      done
while [[ $name = *" "* ]]; do
		echo -e "\e[41mThe name can't contain spaces\e[0m"
read -e -p "Enter the name of the database you want to create > " name
           echo           
      done
	while [[ ^$name =~ [1-9:!\|@\{#$%\&*\`~+=?.\>\<,\;:\_\] ]]; do
		echo -e "\e[41mYou can't enter these characters \e[0m"
		read -e -p "Enter the name of the database you want to create > " name
           echo           
      done
while ! [[ -d ./dbs/$name ]]; do
			echo -e "\e[41mthis database doesn't exist\e[0m"
	
	read -e -p "Enter the name of the database you want to create > " name
           echo  
done
    if [[ -e ./dbs/$name ]]; then
                rm -r ./dbs/$name
		echo -e "\e[44mYour database is deleted  sucessfully \e[0m"
		
      fi
   
;;
5) exit
esac
done





